// Preview stub for '@airtable/blocks/interface/models'. String values match
// the real FieldType enum.
export const FieldType = {
    SINGLE_LINE_TEXT: 'singleLineText',
    MULTILINE_TEXT: 'multilineText',
    RICH_TEXT: 'richText',
    EMAIL: 'email',
    URL: 'url',
    PHONE_NUMBER: 'phoneNumber',
    NUMBER: 'number',
    CURRENCY: 'currency',
    PERCENT: 'percent',
    RATING: 'rating',
    DURATION: 'duration',
    COUNT: 'count',
    AUTO_NUMBER: 'autoNumber',
    DATE: 'date',
    DATE_TIME: 'dateTime',
    CREATED_TIME: 'createdTime',
    LAST_MODIFIED_TIME: 'lastModifiedTime',
    SINGLE_SELECT: 'singleSelect',
    MULTIPLE_SELECTS: 'multipleSelects',
    CHECKBOX: 'checkbox',
    SINGLE_COLLABORATOR: 'singleCollaborator',
    MULTIPLE_COLLABORATORS: 'multipleCollaborators',
    MULTIPLE_RECORD_LINKS: 'multipleRecordLinks',
    MULTIPLE_ATTACHMENTS: 'multipleAttachments',
    FORMULA: 'formula',
    ROLLUP: 'rollup',
    MULTIPLE_LOOKUP_VALUES: 'multipleLookupValues',
    EXTERNAL_SYNC_SOURCE: 'externalSyncSource',
    BARCODE: 'barcode',
    BUTTON: 'button',
    AI_TEXT: 'aiText',
};
